import ProductImage from '../public/images/products/product-image.png';

export const products = [
  { id: 1, name: 'M-terraDry', image: ProductImage, price: 19.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 2, name: 'M-Hive', image: ProductImage, price: 24.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 3, name: 'M-Geoshield', image: ProductImage, price: 15.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 4, name: 'M-GeoShade', image: ProductImage, price: 22.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 5, name: 'M-Defend', image: ProductImage, price: 14.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 6, name: 'M-Detox', image: ProductImage, price: 18.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 7, name: 'MPerform', image: ProductImage, price: 21.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 8, name: 'M-Aquacare', image: ProductImage, price: 20.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 9, name: 'Diatomite', image: ProductImage, price: 19.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 10, name: 'Product 10', image: ProductImage, price: 23.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 11, name: 'Product 11', image: ProductImage, price: 25.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
  
  { id: 12, name: 'Product 12', image: ProductImage, price: 16.99, quantity: '$ 2.99/500g', description: "A Natural, Organic & Eco-Friendly Solution that aligns with Your Needs. Unleash your crops' potential with M-TerraBoost, a soil energiser that nurtures from seedling to harvest. Watch as your crops flourish, resource needs diminish, and resilience soars. Join the revolution of sustainable agriculture to help the soil come alive & strengthen the plants from within." },
];
